=== acionescu/netcell/repository/dtds/entry-point.dtd
<!ELEMENT configuration (cfg-handler*) >

<!ELEMENT cfg-handler ( property*, local-cfg-handler* ) >
<!ATTLIST cfg-handler class CDATA #IMPLIED >
<!ATTLIST cfg-handler tag-ref CDATA #IMPLIED >
<!ATTLIST cfg-handler id CDATA #REQUIRED >
<!ATTLIST cfg-handler default-class CDATA #IMPLIED >

<!ELEMENT local-cfg-handler ( #PCDATA ) >
<!ATTLIST local-cfg-handler id CDATA #IMPLIED >
<!ATTLIST local-cfg-handler tag-ref CDATA #REQUIRED >
<!ATTLIST local-cfg-handler tag-name CDATA #REQUIRED >

<!ELEMENT property ( value? ) >
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST property value-ref NMTOKEN #IMPLIED >

<!ELEMENT entry ( value? , value-ref? ) >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry value CDATA #IMPLIED >
<!ATTLIST entry type CDATA #IMPLIED >

<!ELEMENT value ( #PCDATA | list | map )* >

<!ELEMENT list ( value*, value-ref*) >

<!ELEMENT map ( entry+ ) >

<!ELEMENT value-ref ( #PCDATA ) >

<!ELEMENT file ( #PCDATA ) >

<!ELEMENT files ( file* , dir* )* >

<!ELEMENT dir (#PCDATA) >
<!ATTLIST dir filter CDATA #IMPLIED >
<!ATTLIST dir recursive (false | true) #IMPLIED >

=== acionescu/netcell/repository/xmls/cfg/dynamic-handlers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../../dtds/entry-point.dtd">
<configuration>
	<cfg-handler id="entityRefCfgHandler"
		class="ro.zg.cfgengine.core.configuration.handlers.DependencyConfigurationHandler">
		<property name="hasIdAttribute" value="false"></property>
		<property name="referenceAttributeName" value="ref-id"></property>
	</cfg-handler>
	<cfg-handler id="simpleCustomCfgHandler"
		class="ro.zg.cfgengine.core.configuration.handlers.BaseConfigurationHandler">
		<property name="hasIdAttribute" value="false"></property>
	</cfg-handler>
	<cfg-handler id="dynamicExecutionEntityHandler"
		class="ro.zg.cfgengine.core.configuration.handlers.TypeDecoratorConfigurationHandler"
		default-class="ro.zg.util.execution.test.DynamicExecutionWrapper">
		<property name="hasIdAttribute" value="false" />
		<property name="typeAttributeName" value="logic-type" />
		<property name="typesToProperties">
			<value>
				<map>
					<entry key="config" value="config"></entry>
				</map>
			</value>
		</property>
		<property name="localConfigurationHandlers">
			<value>
				<map>
					<entry key="entity">
						<value-ref>dynamicExecutionEntityConfigHandler</value-ref>
					</entry>
				</map>
			</value>
		</property>
	</cfg-handler>
	<cfg-handler id="dynamicExecutionEntityConfigHandler"
		class="ro.zg.cfgengine.core.configuration.handlers.BaseConfigurationHandler"
		default-class="ro.zg.util.execution.test.DynamicExecutionWrapperConfiguration">
		<property name="hasIdAttribute" value="false" />
		<property name="defaultInitMethod" value="init"></property>
	</cfg-handler>
	
	
		<cfg-handler id="logicTypeHandler"
		class="ro.zg.cfgengine.core.configuration.handlers.TypeConfigurationHandler">
		<property name="hasIdAttribute" value="false" />
		<property name="typeAttributeName" value="logic-type"></property>
		<property name="localConfigurationHandlers">
			<value>
				<map>
<!--					<entry key="preparator-inspector">-->
<!--						<value-ref>preparatorInspectorHandler</value-ref>-->
<!--					</entry>-->
<!--					<entry key="left-join">-->
<!--						<value-ref>leftJoinHandler</value-ref>-->
<!--					</entry>-->
<!--					<entry key="right-join">-->
<!--						<value-ref>rightJoinHandler</value-ref>-->
<!--					</entry>-->
<!--					<entry key="pipeline">-->
<!--						<value-ref>pipelineHandler</value-ref>-->
<!--					</entry>-->
<!--					<entry key="config-wrapper">-->
<!--						<value-ref>configHandler</value-ref>-->
<!--					</entry>-->
					<entry key="dynamic-wrapper">
						<value-ref>dynamicExecutionEntityHandler</value-ref>
					</entry>
				</map>
			</value>
		</property>
	</cfg-handler>
	
	<cfg-handler id="rootHandler"
		class="ro.zg.cfgengine.core.configuration.handlers.BaseConfigurationHandler">
		<property name="localConfigurationHandlers">
			<value>
				<map>
<!--					<entry key="component">-->
<!--						<value-ref>componentWrapperHandler</value-ref>-->
<!--					</entry>-->
<!--					<entry key="component-context">-->
<!--						<value-ref>componentPipelineWrapperHandler</value-ref>-->
<!--					</entry>-->
					<entry key="entity">
						<value-ref>logicTypeHandler</value-ref>
					</entry>
					<entry key="entity-ref">
						<value-ref>entityRefCfgHandler</value-ref>
					</entry>
				</map>
			</value>
		</property>
	</cfg-handler>
</configuration>
