=== acionescu/netcell/repository/dtds/script-dao-commands.dtd
<!ELEMENT command (parameters?, script)>
<!ATTLIST command name NMTOKEN #REQUIRED>
<!ATTLIST command type NMTOKEN #REQUIRED>

<!ELEMENT parameters (parameter*)>

<!ELEMENT parameter EMPTY >
<!ATTLIST parameter name NMTOKEN #REQUIRED>

<!ELEMENT script (#PCDATA)>

=== acionescu/netcell/repository/root/datasources/problems_db/commands/ro_problems_data_get-entities-list-with-filters-count.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "../../../../dtds/script-dao-commands.dtd">
<command name="ro.problems.data.get-entities-list-with-filters-count" type="SQL.QUERY">
         <parameters>
                     <parameter name="parentId" />
                     <parameter name="depth" />
                     <parameter name="searchString" />
                     <parameter name="entityType" />
                     <parameter name="tag" />
                     <parameter name="status" />
                     <parameter name="globalStatus" />
                     <parameter name="userId" />
                     <parameter name="userActionColumn" />
                     <parameter name="filterByUser" />
               </parameters>
      <script>
      WITH RECURSIVE subentities_list(id, complex_type_id,complex_type, parent_entity_id, depth) AS (
        SELECT e.id, cet.id complex_type_id,cet.complex_type, e.parent_entity_id, 0
        FROM entities e, complex_entity_type cet
        where e.parent_entity_id=$parentId
        and e.complex_entity_type_id=cet.id
        
      UNION ALL
        SELECT e.id, cet.id complex_type_id,cet.complex_type, e.parent_entity_id, eg.depth + 1
        FROM entities e, subentities_list eg, complex_entity_type cet
        WHERE eg.id = e.parent_entity_id
        and e.complex_entity_type_id=cet.id
        #if($depth)
        and eg.depth &lt; $depth
        #end
)
select 
#if($entityType || $userActionColumn)
count(distinct(e.id)) 
#else
count(*)
#end
from entities e
join subentities_list sl on (e.id=sl.id)
#if(!$entityType &amp;&amp; !$userActionColumn)
join activity_log al on (e.id=al.entity_id)
#end
where 1=1
#if($entityType)
and sl.complex_type='$entityType'
#end
#if($searchString)
and (lower(e.title) like '%$searchString%' or lower(e.content) like '%$searchString%')
#end
#if($tag)
and exists (select 1 from entities_tags et,tags t where et.entity_id=e.id and et.tag_id=t.id and t.tag='$tag')
#end
#if($status)
and exists (select 1 from entities_users eu,statuses s where eu.entity_id=e.id and eu.status_id=s.id and s.status='$status')
#end
#if($globalStatus)
and exists (select 1 from entities_statuses es,statuses s where entity_id=e.id and es.status_id=s.id and s.status='$globalStatus')
#end
#if($userActionColumn)
and exists (select 1 from entities_users where entity_id=e.id #if($filterByUser)and user_id=$userId#end and $userActionColumn is not null)
#end

   </script>
</command>

=== acionescu/netcell/repository/root/datasources/problems_db/commands/ro_problems_data_save-entities-users-date.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "../../../../dtds/script-dao-commands.dtd">
<command name="ro.problems.data.save-entities-users-date" type="SQL.UPDATE">
         <parameters>
                     <parameter name="entityId" />
                     <parameter name="userId" />
                     <parameter name="vote" />
                     <parameter name="priority" />
                     <parameter name="statusId" />
                     <parameter name="flag" />
               </parameters>
      <script>
      update entities_users
#if($flag=="vote" )
#if($vote)
set vote='$vote'
#else
set vote=null
#end
#elseif($flag=="priority")
#if($priority )
set priority=$priority
#else
set priority=null
#end
#elseif($flag=="status")
#if($statusId != -1)
set status_id=$statusId
#else
set status_id=null
#end
#end
where entity_id=$entityId and user_id=$userId

   </script>
</command>

=== acionescu/netcell/repository/root/datasources/problems_db/commands/ro_problems_data_create-entity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "../../../../dtds/script-dao-commands.dtd">
<command name="ro.problems.data.create-entity" type="SQL.UPDATE">
         <parameters>
                     <parameter name="userId" />
                     <parameter name="entityType" />
                     <parameter name="complexType" />
                     <parameter name="parentId" />
                     <parameter name="title" />
                     <parameter name="content" />
                     <parameter name="entityId" />
               </parameters>
      <script>
      insert into entities(id,creator_id,entity_type_id,complex_entity_type_id,parent_entity_id,title,content)
values(
$entityId
,$userId
,(select id from entity_types  where type='$entityType')
,(select id from complex_entity_type  where complex_type ='$complexType')
,$parentId
,'$title'
,'$content'
)
   </script>
</command>

=== acionescu/netcell/repository/root/datasources/crawler-test-db/commands/test_http_insert-into-urls-symbols.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "../../../../dtds/script-dao-commands.dtd">
<command name="test.http.insert-into-urls-symbols" type="SQL.UPDATE">
         <parameters>
                     <parameter name="urlId" />
                     <parameter name="fragment" />
                     <parameter name="parentFragment" />
                     <parameter name="symbolId" />
                     <parameter name="symbolPos" />
               </parameters>
      <script>
      insert into urls_symbols
values($urlId,$fragment,$parentFragment,$symbolId,$symbolPos)
   </script>
</command>

=== acionescu/netcell/repository/root/datasources/problems_db/commands/ro_problems_data_get-entities-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "../../../../dtds/script-dao-commands.dtd">
<command name="ro.problems.data.get-entities-list" type="SQL.QUERY">
         <parameters>
                     <parameter name="withContent" />
                     <parameter name="subtypesList" />
                     <parameter name="parentId" />
                     <parameter name="entityType" />
                     <parameter name="sortList" />
                     <parameter name="itemsOnPage" />
                     <parameter name="pageNumber" />
                     <parameter name="userId" />
                     <parameter name="depth" />
                     <parameter name="entityId" />
                     <parameter name="searchString" />
                     <parameter name="complexTypesIds" />
                     <parameter name="tag" />
                     <parameter name="status" />
                     <parameter name="globalStatus" />
                     <parameter name="userActionColumn" />
                     <parameter name="filterByUser" />
               </parameters>
      <script>
      #if($parentId)
WITH RECURSIVE subentities_list(id, complex_type_id,complex_type, parent_entity_id, depth) AS (
        SELECT e.id, cet.id complex_type_id,cet.complex_type, e.parent_entity_id, 0
        FROM entities e, complex_entity_type cet
        where e.parent_entity_id=$parentId
        and e.complex_entity_type_id=cet.id
        
      UNION ALL
        SELECT e.id, cet.id complex_type_id,cet.complex_type, e.parent_entity_id, eg.depth + 1
        FROM entities e, subentities_list eg, complex_entity_type cet
        WHERE eg.id = e.parent_entity_id
        and e.complex_entity_type_id=cet.id
        #if($depth)
        and eg.depth &lt; $depth
        #end
)
#elseif($entityId)
WITH RECURSIVE entity_upstream_hierarchy(id, complex_type, parent_entity_id, depth) AS (
        SELECT e.id, cet.complex_type, e.parent_entity_id, 0
        FROM entities e, complex_entity_type cet
        where e.id=$entityId
        and e.complex_entity_type_id=cet.id
        
      UNION ALL
        SELECT e.id, cet.complex_type, e.parent_entity_id, eg.depth + 1
        FROM entities e, entity_upstream_hierarchy eg, complex_entity_type cet
        WHERE e.id = eg.parent_entity_id
	and cet.complex_type in ('ISSUE','SOLUTION')
        and e.complex_entity_type_id=cet.id
       #if($depth)
        and eg.depth &lt; $depth
       #end
)
#end
select 
e.id
, e.title
#if($withContent)
, e.content
#else
, substring(e.content from 1 for 1000) content_preview
#end
, e.insert_date
, cet.complex_type 
, e.creator_id
, idsList.depth
,votes.pro_votes
,votes.opposed_votes	
,votes.total_votes
, case (votes.total_votes)
when 0 then 0
else (votes.pro_votes-votes.opposed_votes)
end popularity_index
,ep.priority general_priority
,gs.status general_status
#if($userId)
,eu.vote user_vote
,eu.last_vote_update
,eu.priority
,eu.last_priority_update
,st.status
,eu.last_status_update
#end
#if($subtypesList)
, $subtypesList.size() subtypes_count
#foreach( $entityContext in $subtypesList.getValues())
#set($currentTable = "e${velocityCount}.id")
,count(distinct($currentTable)) $entityContext.getValue("simple_subtype")_subtype_count
#end	
#end
--if is a recent activity list
#if($parentId &amp;&amp; !$entityType &amp;&amp; !$userActionColumn)
-- bring the action type
,actLog.action_type_id
,(select type from action_types where id=actLog.action_type_id) action_type
-- bring also the parent id and title
,e.parent_entity_id
,(select title from entities where id=e.parent_entity_id) parent_title
#end
from entities e
left outer join (
select 
e2.id entity_id
,sum(case v.vote
	when 'y' then 1
	else 0
	end) pro_votes
,sum(case v.vote
	when 'n' then 1
	else 0
	end) opposed_votes
,count(v.vote) total_votes	
from entities e2
left outer join entities_users v on (e2.id = v.entity_id)
group by e2.id	
) votes on (e.id = votes.entity_id)
#if($subtypesList)
#foreach( $entityContext in $subtypesList.getValues())
#set($currentTable = "e${velocityCount}")
left outer join entities $currentTable on (e.id = ${currentTable}.parent_entity_id and ${currentTable}.complex_entity_type_id=$entityContext.getValue("id"))
#end
#end
#if($userId)
left outer join entities_users eu on(e.id = eu.entity_id and eu.user_id=$userId)
left outer join statuses st on(eu.status_id = st.id)
#end
left outer join entities_priorities ep on (e.id=ep.entity_id)
left outer join entities_statuses es on (e.id=es.entity_id)
left outer join statuses gs on(es.status_id=gs.id)
inner join complex_entity_type cet on (e.complex_entity_type_id = cet.id)
#if($parentId)
#if($entityType)
join subentities_list idsList on (e.id = idsList.id and idsList.complex_type='$entityType')
#elseif($complexTypesIds)
join subentities_list idsList on (e.id = idsList.id and idsList.complex_type_id in $complexTypeIds)
#else
join subentities_list idsList on (e.id = idsList.id)
#if(!$userActionColumn)
join activity_log actLog on (e.id = actLog.entity_id)
#end
#end
#elseif($entityId)
join entity_upstream_hierarchy idsList on (e.id = idsList.id )
#end
where 1=1
#if($searchString)
and lower(e.title) like '%$searchString%' or lower(e.content) like '%$searchString%'
#end
#if($tag)
and exists (select 1 from entities_tags et,tags t where et.entity_id=e.id and et.tag_id=t.id and t.tag='$tag')
#end
#if($status)
and st.status='$status'
#end
#if($globalStatus)
and gs.status='$globalStatus'
#end
#if($userActionColumn)
and exists (select 1 from entities_users where entity_id=e.id #if($filterByUser)and user_id=$userId#end and $userActionColumn is not null)
#end
group by 
e.id
, e.title
#if($withContent)
, e.content
#else
,content_preview
#end
, e.insert_date
, e.last_update
, cet.complex_type
, e.creator_id
, idsList.depth
,votes.pro_votes,votes.opposed_votes,votes.total_votes
,ep.priority,gs.status
#if($userId)
,eu.vote
,eu.last_vote_update
,eu.priority
,eu.last_priority_update
,st.status
,eu.last_status_update
#end
#if($parentId &amp;&amp; !$entityType &amp;&amp; !$userActionColumn)
,e.parent_entity_id
,actLog.action_type_id
,actLog.action_timestamp
#end
order by $sortList
limit $itemsOnPage offset $itemsOnPage * ( $pageNumber - 1 )

   </script>
</command>
