=== acionescu/netcell/repository/dtds/workflow-engine.dtd
<!ELEMENT list ( value* , value-ref*) >

<!ELEMENT map ( entry+ ) >

<!ELEMENT property ( value? ) >
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST property value-ref NMTOKEN #IMPLIED >
<!ATTLIST property depth CDATA #IMPLIED >

<!ELEMENT entry ( value? , value-ref?, value-type? ) >
<!ATTLIST entry key CDATA #REQUIRED >
<!ATTLIST entry value CDATA #IMPLIED >

<!ELEMENT resource ( property* ) >
<!ATTLIST resource class CDATA #REQUIRED >
<!ATTLIST resource id NMTOKEN #IMPLIED >
<!ATTLIST resource init-method CDATA #IMPLIED >
<!ATTLIST resource destroy-method CDATA #IMPLIED >

<!ELEMENT resources ( resource* ) >

<!ELEMENT value ( #PCDATA | list | map | resource)* >

<!ELEMENT value-ref ( #PCDATA ) >

<!ELEMENT value-type EMPTY >
<!ATTLIST value-type value CDATA #REQUIRED >
<!ATTLIST value-type type CDATA #REQUIRED >

<!ELEMENT components ( component*,component-context* ) >

<!ELEMENT component-context ( input-parameters?, component) >
<!ATTLIST component-context id NMTOKEN #REQUIRED >

<!ELEMENT component ( component-configuration?) >
<!ATTLIST component class CDATA #REQUIRED >
<!ATTLIST component id NMTOKEN #IMPLIED >

<!ELEMENT component-configuration ( property* )>
<!ATTLIST component-configuration class CDATA #REQUIRED >
<!ATTLIST component-configuration id NMTOKEN #IMPLIED >
<!ATTLIST component-configuration init-method CDATA #IMPLIED >
<!ATTLIST component-configuration destroy-method CDATA #IMPLIED >

<!ELEMENT workflows ( workflow-context* ) >

<!ELEMENT workflow-context ( listener*, workflow-configuration?, session?, listener*, workflow ) >
<!ATTLIST workflow-context id NMTOKEN #REQUIRED >

<!ELEMENT session ( session-config ) >
<!ATTLIST session session-manager-ref NMTOKEN #REQUIRED >

<!ELEMENT session-config ( id-params?, params-to-save, session-actions ) >
<!ATTLIST session-config timeout CDATA #REQUIRED >
<!ATTLIST session-config has-id-params CDATA #REQUIRED >

<!ELEMENT id-params ( id-param* )>

<!ELEMENT id-param EMPTY>
<!ATTLIST id-param name CDATA #REQUIRED >

<!ELEMENT params-to-save ( parameter-to-save* )>

<!ELEMENT parameter-to-save EMPTY >
<!ATTLIST parameter-to-save name CDATA #REQUIRED >
 
 <!ELEMENT session-actions ( session-action* ) >
 
 <!ELEMENT session-action EMPTY>
 <!ATTLIST session-action exit-point CDATA #REQUIRED >
 <!ATTLIST session-action action ( SAVE | DELETE ) #REQUIRED >
 <!ATTLIST session-action next-comp-id-ref CDATA #IMPLIED >
 
<!ELEMENT listener EMPTY >
<!ATTLIST listener id-ref NMTOKEN #REQUIRED >

<!ELEMENT workflow ( workflow-components, workflow-logic ) >
<!ATTLIST workflow start-comp-id NMTOKEN #REQUIRED >

<!ELEMENT workflow-configuration ( input-parameters?, output-parameters? ) >

<!ELEMENT input-parameters ( input-parameter* ) >

<!ELEMENT input-parameter (validation-rules?, translation-rules?) >
<!ATTLIST input-parameter name CDATA #REQUIRED >
<!ATTLIST input-parameter value CDATA #IMPLIED >
<!ATTLIST input-parameter type CDATA #IMPLIED >
<!ATTLIST input-parameter mandatory ( true | false ) #IMPLIED >

<!ELEMENT validation-rules ( validation-rule* ) >

<!ELEMENT validation-rule ( parameter* ) >

<!ELEMENT translation-rules ( translation-rule* ) >

<!ELEMENT translation-rule ( parameter* ) >

<!ELEMENT output-parameters ( output-parameter* ) >

<!ELEMENT output-parameter ( #PCDATA ) >
<!ATTLIST output-parameter name CDATA #IMPLIED >

<!ELEMENT workflow-components ( workflow-component* ) >

<!ELEMENT workflow-component ( listener*, workflow-component-configuration?, listener* ) >
<!ATTLIST workflow-component local-id CDATA #REQUIRED >
<!ATTLIST workflow-component id-ref CDATA #REQUIRED >

<!ELEMENT workflow-component-configuration ( static-parameters?, dynamic-parameters?, output-parameter-mappings? ) >

<!ELEMENT static-parameters ( parameter* ) >

<!ELEMENT parameter ( value?) >
<!ATTLIST parameter name CDATA #REQUIRED >
<!ATTLIST parameter value CDATA #IMPLIED >
<!ATTLIST parameter type CDATA #IMPLIED >

<!ELEMENT dynamic-parameters ( dynamic-parameter* ) >

<!ELEMENT dynamic-parameter EMPTY >
<!ATTLIST dynamic-parameter local-name CDATA #REQUIRED >
<!ATTLIST dynamic-parameter context-name CDATA #REQUIRED >

<!ELEMENT output-parameter-mappings ( output-parameter-mapping* ) >

<!ELEMENT output-parameter-mapping EMPTY >
<!ATTLIST output-parameter-mapping local-name CDATA #REQUIRED >
<!ATTLIST output-parameter-mapping context-name CDATA #REQUIRED >

<!ELEMENT workflow-logic ( component-exit-points-mappings* ) >

<!ELEMENT component-exit-points-mappings ( exit-point-mapping* ) >
<!ATTLIST component-exit-points-mappings local-comp-id CDATA #REQUIRED >

<!ELEMENT exit-point-mapping EMPTY >
<!ATTLIST exit-point-mapping exit-point CDATA #REQUIRED >
<!ATTLIST exit-point-mapping next-comp-id NMTOKEN #IMPLIED >
<!ATTLIST exit-point-mapping exit CDATA #IMPLIED >

=== acionescu/netcell/repository/root/target/test-classes/root/config/controller/controller-init.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../../../dtds/workflow-engine.dtd">
<resources>
   
   <resource id="distributedServicesManager" class="ro.zg.netcell.control.DistributedServicesManager">
      <property name="entitiesManager">
         <value>
            <resource id="entitiesManager" class="ro.zg.netcell.distributed.EntitiesManagerProxy"></resource>
         </value>
      </property>
      <property name="executionEngine">
         <value>
            <resource id="executionEngine" class="ro.zg.netcell.distributed.ExecutionEngineProxy"></resource>
         </value>
      </property>
      <property name="monitoringManager">
         <value>
            <resource id="monitoringManager" class="ro.zg.netcell.distributed.MonitoringManagerProxy"></resource>
         </value>
      </property>
      <property name="repositoryDir" value="file:///media/disk/work/projects/netcell/repository/"></property>
      <property name="entryPointFile" value="root/config/distributed-services/distributed-services-config.xml"></property>
   </resource>
  
   <resource id="netCellControllerConfiguration"
      class="ro.zg.netcell.control.NetCellControllerConfiguration">
      <property name="servicesManager" value-ref="distributedServicesManager"></property>
   </resource>
   <resource id="NetCellController" class="ro.zg.netcell.control.NetCellController">
      <property name="config" value-ref="netCellControllerConfiguration"></property>
   </resource>
   <resource id="CommandControllerWrapper"
      class="ro.zg.netcell.control.CommandControllerWrapper">
      <property name="wrappedExecutionEntity" value-ref="CommandController"></property>
      <property name="exceptionHandler" value-ref="BorderExceptionHandler"></property>
   </resource>
   <resource id="CommandController" class="ro.zg.netcell.control.CommandController">
      <property name="commandExecutors">
         <value>
            <map>
               <entry key="get_definitions">
                  <value-ref>getDefinitionsCommand</value-ref>
               </entry>
               <entry key="execute">
                  <value-ref>executeEntityCommand</value-ref>
               </entry>
               <entry key="create_entity">
                  <value-ref>createEntityCommand</value-ref>
               </entry>
               <entry key="update_entity">
                  <value-ref>updateEntityCommand</value-ref>
               </entry>
               <entry key="remove_entity">
                  <value-ref>removeEntityCommand</value-ref>
               </entry>
               <entry key="get_definition_types">
                  <value-ref>getDefinitionTypes</value-ref>
               </entry>
            </map>
         </value>
      </property>
   </resource>
   <resource id="getDefinitionsCommand" class="ro.zg.netcell.control.commands.GetDefinitions">
      <property name="netCellController" value-ref="NetCellController"></property>
   </resource>
   <resource id="executeEntityCommand" class="ro.zg.netcell.control.commands.ExecuteEntity">
      <property name="netCellController" value-ref="NetCellController"></property>
   </resource>
   <resource id="createEntityCommand" class="ro.zg.netcell.control.commands.CreateEntity">
      <property name="netCellController" value-ref="NetCellController"></property>
   </resource>
   <resource id="updateEntityCommand" class="ro.zg.netcell.control.commands.UpdateEntity">
      <property name="netCellController" value-ref="NetCellController"></property>
   </resource>
   <resource id="getDefinitionTypes" class="ro.zg.netcell.control.commands.GetDefinitionTypes">
      <property name="netCellController" value-ref="NetCellController"></property>
   </resource>
   <resource id="removeEntityCommand" class="ro.zg.netcell.control.commands.RemoveEntity">
       <property name="netCellController" value-ref="NetCellController"></property>
   </resource>
</resources>

=== acionescu/netcell/repository/root/target/test-classes/xmls/engine/components.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE components SYSTEM "../../dtds/workflow-engine.dtd">
<components>
	<component id="DummyComponent" class="ro.zg.synapse.engine.configuration.DummyWorkFlowComponent">
	</component>
	
	<component id="ExceptionalComponent" class="ro.zg.synapse.engine.configuration.ExceptionThrowingComponent">
	</component>
	
	<component id="Comparator" class="ro.zg.synapse.engine.components.ComparatorComponent">
		<component-configuration>
			<input-parameters>
				<input-parameter name="referenceValue" mandatory="true"/>
				<input-parameter name="comparedValue" mandatory="true"/>
			</input-parameters>
		</component-configuration>
	</component>
	
	<component id="InputMapper" class="ro.zg.synapse.engine.components.InputMapperComponent">
		<component-configuration>
			<input-parameters>
				<input-parameter name="filterParameters" mandatory="true"></input-parameter>
				<input-parameter name="mappedOutput" mandatory="true"></input-parameter>
			</input-parameters>
		</component-configuration>
	</component>
</components>

=== acionescu/netcell/repository/xmls/receivers/cas-formatters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../../dtds/workflow-engine.dtd">
<resources>
   <resource id="CasResponseFormatter"
      class="ro.zg.netcell.control.commands.formatters.AbstractObjectFormatter"
      init-method="init">
      <property name="formatters">
         <value>
            <map>
               <entry key="CommandResponse">
                  <value-ref>CommandResponseFormatter</value-ref>
               </entry>
               <entry key="GenericNameValue">
                  <value-ref>CasGenericNameValueFormatter</value-ref>
               </entry>
               <entry key="Collection">
                  <value-ref>CollectionFormatter</value-ref>
               </entry>
               <entry key="GenericNameValueContext">
                  <value-ref>GenericNameValueContextFormatter</value-ref>
               </entry>
               <entry key="GenericNameValueList">
                  <value-ref>GenericNameValueListFormatter</value-ref>
               </entry>
            </map>
         </value>
      </property>
      <property name="defaultFormatter" value-ref="reflectiveFormatter"></property>
   </resource>
   <resource id="reflectiveFormatter"
      class="ro.zg.netcell.control.commands.formatters.ReflectiveFormatter"></resource>
   <resource id="CasGenericNameValueFormatter"
      class="ro.zg.netcell.control.commands.formatters.GenericNameValueFormatter">
   </resource>
   <resource id="CommandResponseFormatter"
      class="ro.zg.netcell.control.commands.formatters.CommandResponseFormatter">
   </resource>
   <resource id="CollectionFormatter"
      class="ro.zg.netcell.control.commands.formatters.CollectionFormatter">
      <property name="startElement" value="["></property>
      <property name="endElement" value="]"></property>
   </resource>
   <resource id="GenericNameValueContextFormatter" class="ro.zg.netcell.control.commands.formatters.GenericNameValueContextFormatter">
      <property name="startElement" value="{"></property>
      <property name="endElement" value="}"></property>
   </resource>
    <resource id="GenericNameValueListFormatter" class="ro.zg.netcell.control.commands.formatters.GenericNameValueListFormatter">
      <property name="startElement" value="["></property>
      <property name="endElement" value="]"></property>
   </resource>
</resources>

=== acionescu/netcell/repository/xmls/control/command-executors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../../dtds/workflow-engine.dtd">


<resources>
	<resource id="CommandRouter" class="ro.zg.synapse.control.commands.executors.CommandRouter">
		<property name="commandExecutors">
			<value>
				<map>
					<entry key="execute">
						<value-ref>WorkFlowRequestExecutor</value-ref>
					</entry>
				</map>
			</value>
		</property>
	</resource>
	
	<resource id="CommandRouterContext" class="ro.zg.synapse.engine.EntityExecutionContextImpl">
		<property name="exceptionHandler" value-ref="BorderExceptionHandler"></property>
		<property name="wrappedExecutionEntity" value-ref="CommandRouter"></property>
	</resource>
	
	<resource id="CommandRouterWrapper" class="ro.zg.synapse.control.commands.executors.CommandExecutorWrapper">
		<property name="entityExecutionContext" value-ref="CommandRouterContext"></property>
	</resource>
	
	<!-- controller -->
	<resource id="CommandController" class="ro.zg.synapse.control.commands.executors.CommandController">
		<property name="executorComponents">
			<value>
				<map>
					<entry key="execute">
						<value-ref>WorkFlowRequestExecutorComponent</value-ref>
					</entry>
				</map>
			</value>
		</property>
	</resource>
	
		
	<resource id="CommandControllerContext" class="ro.zg.synapse.engine.EntityExecutionContextImpl">
		<property name="exceptionHandler" value-ref="BorderExceptionHandler"></property>
		<property name="wrappedExecutionEntity" value-ref="CommandController"></property>
	</resource>
	
	<resource id="CommandControllerWrapper" class="ro.zg.synapse.control.commands.executors.CommandExecutorWrapper">
		<property name="entityExecutionContext" value-ref="CommandControllerContext"></property>
	</resource>
	
	<!-- execute -->
	<resource id="WorkFlowRequestExecutor" class="ro.zg.synapse.control.commands.executors.WorkFlowRequestExecutor"></resource>
	
	
</resources>

=== acionescu/netcell/repository/root/target/test-classes/xmls/receivers/receivers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../../dtds/workflow-engine.dtd">

<resources>
	<resource id="CasCommandsSocketReceiver" class="ro.zg.util.io.SocketReceiver">
		<property name="listenPort" value="9000"></property>
		<property name="processor" value-ref="CasCommandsProcessor"></property>
	</resource>
	
	<resource id="CasCommandsProcessor" class="ro.zg.util.io.SocketProcessor">
		<property name="socketWorkerFactory" value-ref="CasCommandsWorkerFactory"></property>
	</resource>
	
	<resource id="CasCommandsWorkerFactory" class="ro.zg.netcell.control.receivers.CasCommandReceiverFactory">
		<property name="interpreter" value-ref="CasInterpreterWrapper"></property>
	</resource>
	
	<!-- RMI -->
	<resource id="RmiCommandReceiver" class="ro.zg.netcell.control.receivers.RmiCommandReceiver">
		<property name="bindName" value="NetcellRmiReceiver"></property>
		<property name="bindPort" value="9001"></property>
		<property name="registryPort" value="2000"></property>
	</resource>
</resources>
