=== acionescu/netcell/repository/root/target/test-classes/dtds/entities.dtd
<!ELEMENT list ( value* , value-ref*) >

<!ELEMENT map ( entry+ ) >

<!ELEMENT property ( value? ) >
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST property value-ref NMTOKEN #IMPLIED >
<!ATTLIST property depth CDATA #IMPLIED >

<!ELEMENT entry ( value? , value-ref?, value-type? ) >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry value CDATA #IMPLIED >
<!ATTLIST entry type CDATA #IMPLIED >

<!ELEMENT entity ( value? | entity* | entity-ref* | property* )* >
<!ATTLIST entity type NMTOKEN #IMPLIED >
<!ATTLIST entity logic-type NMTOKEN #IMPLIED >
<!ATTLIST entity id NMTOKEN #IMPLIED >
<!ATTLIST entity value NMTOKEN #IMPLIED >
<!ATTLIST entity class NMTOKEN #IMPLIED >
<!ATTLIST entity init-method CDATA #IMPLIED >
<!ATTLIST entity destroy-method CDATA #IMPLIED >

<!ELEMENT entity-ref EMPTY >
<!ATTLIST entity-ref type NMTOKEN #IMPLIED >
<!ATTLIST entity-ref ref-id NMTOKEN #REQUIRED >

<!ELEMENT entities ( entity* ) >

<!ELEMENT resource ( property* ) >
<!ATTLIST resource class NMTOKEN #REQUIRED >
<!ATTLIST resource id NMTOKEN #IMPLIED >
<!ATTLIST resource init-method CDATA #IMPLIED >
<!ATTLIST resource destroy-method CDATA #IMPLIED >

<!ELEMENT resources ( resource* ) >

<!ELEMENT value ( #PCDATA | list | map | resource | entity )* >

<!ELEMENT value-ref ( #PCDATA ) >

<!ELEMENT value-type EMPTY >
<!ATTLIST value-type value NMTOKEN #REQUIRED >
<!ATTLIST value-type type NMTOKEN #REQUIRED >

=== acionescu/netcell/repository/root/entities/workflows/ro/problems/flows/get-statuses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
   <entity id="ro.problems.flows.get-statuses" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>$workflowDefinition.getDescription()</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  												<entry key="localParameters">
							<value>
								<list>
																		<value>
										<entity type="local-parameter">
	<property name="name" value="result"></property>
		<property name="type" value="List[Context[]]"></property>
		</entity>								</value>
																	</list>
							</value>
						</entry>
												<entry key="executionEntity">
							<value>
																<entity type="workflow" logic-type="dynamic-wrapper">
   <entity logic-type="config">
      <entity logic-type="executor">
         <entity-ref ref-id="workFlow" />
      </entity>
<!--      <entity logic-type="original-input-name">-->
<!--         <value>inputContext</value>-->
<!--      </entity>-->
      <entity type="workflow-params" logic-type="static-parameters">
         <value>
            <map>
               <entry key="defaultEntryPointId" value="ro.problems.data.get-statuses-most-used_1">
               </entry>
               <entry key="components">
                  <value>
                     <map>
                                                 <entry key="ro.problems.data.get-statuses-most-used_1">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="ro.problems.data.get-statuses-most-used" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
											</entity>
	</entity>
</entity>		<entity logic-type="output-params-mappings">
		<value>
			<map>
								<entry key="result" value="result" />
							</map>
		</value>
	</entity>
		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="exitLabel" value="exit" />
   </entity>               
                                                </entity>                           </value>
                        </entry>
                                             </map>
                  </value>
               </entry>
            </map>
         </value>
      </entity>
      <entity logic-type="dynamic-parameters">
         <value>
            <map>
               <entry key="inputContext" value="origContext"></entry>
               <entry key="entryPointId" value="entryPointId"></entry>
               <entry key="isAsyncContext" value="isAsyncContext"></entry>
            </map>
         </value>
      </entity>
   </entity>
</entity>						</value>
						</entry>
												<entry key="outputParameters">
							<value>
								<list>
									
																		<value>
										<entity type="output-parameter">
	<property name="name" value="exit"></property>
		<property name="type" value="String"></property>
	</entity>								</value>
																		<value>
										<entity type="output-parameter">
	<property name="name" value="result"></property>
		<property name="type" value="List[Context[]]"></property>
	</entity>								</value>
																	</list>
							</value>
						</entry>
											</map>
				</value>
			</entity>
			<entity logic-type="original-input-name">
				<value>inputContext</value>
			</entity>
			<entity logic-type="executor">
				<entity-ref ref-id="workflowAdapterEntity" />
			</entity>
		</entity>
	</entity>
</entities>

=== acionescu/netcell/repository/root/datasources/http-client/connection-manager-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../dtds/entities.dtd">
<entities>
   <entity id="http-client-connection-manager" type="connection-manager"
      logic-type="http">
      <property name="dataSourceDefinition">
         <value>
            <entity id="http-client" type="datasource-definition">
               <property name="datasourceType" value="HTTP"></property>
               <property name="configData">
   <value>
      <entity type="config-data">
                     <property name="userInputParams">
            <value>
               <map>
                                      <entry key="USER_AGENT">
   <value>
      <entity type="user-input-parameter">
         <property name="name" value="USER_AGENT"></property>
                  <property name="value" value="Mozilla/5.0 (X11; U; Linux i686; pl-PL; rv:1.9.0.2) Gecko/20121223 Ubuntu/9.25 (jaunty) Firefox/3.8"></property>
                           <property name="type" value="String"></property>
                           <property name="inputType" value="UNKNOWN_VALUE"></property>
                        </entity>
   </value>
</entry>                                      <entry key="MAX_TOTAL_CONNECTIONS">
   <value>
      <entity type="user-input-parameter">
         <property name="name" value="MAX_TOTAL_CONNECTIONS"></property>
                  <property name="value" value="50"></property>
                           <property name="type" value="Integer"></property>
                           <property name="inputType" value="UNKNOWN_VALUE"></property>
                        </entity>
   </value>
</entry>                                      <entry key="CONNECTION_TIMEOUT">
   <value>
      <entity type="user-input-parameter">
         <property name="name" value="CONNECTION_TIMEOUT"></property>
                  <property name="value" value="15000"></property>
                           <property name="type" value="Integer"></property>
                           <property name="inputType" value="UNKNOWN_VALUE"></property>
                        </entity>
   </value>
</entry>                                </map>
            </value>
         </property>
               
                     
                  </entity>
   </value>
</property>            </entity>
         </value>
      </property>
   </entity>
</entities>

=== acionescu/netcell/repository/root/entities/workflows/test/testEmbededFlow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
   <entity id="test.testEmbededFlow" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>This is how a workflow will look like</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  <entry key="inputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="input-parameter">
                                 <property name="name" value="enteredValue"></property>
                                 <property name="type" value="Number"></property>
                                 <property name="mandatory"
                                    value="true"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
                  <entry key="executionEntity">
                     <value>
                        <entity type="workflow" logic-type="dynamic-wrapper">
                           <entity logic-type="config">
                              <entity logic-type="executor">
                                 <entity-ref ref-id="workFlow" />
                              </entity>
                              <entity logic-type="original-input-name">
                                 <value>fullInputContext</value>
                              </entity>
                              <entity type="workflow-params"
                                 logic-type="static-parameters">
                                 <value>
                                    <map>
                                       <entry key="defaultEntryPointId"
                                          value="comp1">
                                       </entry>
                                       <entry key="components">
                                          <value>
                                             <map>
                                                <entry key="comp1">
                                                   <value>
                                                      <entity
                                                         type="workflow-component">
                                                         <entity
                                                            type="component"
                                                            logic-type="component">
                                                            <entity
                                                               logic-type="dynamic-wrapper">
                                                               <entity
                                                                  logic-type="config">
                                                                  <entity
                                                                     logic-type="executor">
                                                                     <entity-ref
                                                                        ref-id="core.logic.embeded-flow" />
                                                                  </entity>
                                                                  <entity
                                                                     logic-type="original-input-name">
                                                                     <value>argsContext</value>
                                                                  </entity>
                                                                  <entity
                                                                     logic-type="static-parameters">
                                                                     <value>
                                                                        <map>
                                                                           <entry key="fid">
                                                                              <value-type value="generatedFlow2" type="String" />
                                                                           </entry>
                                                                        </map>
                                                                     </value>
                                                                  </entity>
                                                                  <entity
                                                                     logic-type="dynamic-parameters">
                                                                     <value>
                                                                        <map>
                                                                           <entry key="enteredValue" value="enteredValue" />
                                                                        </map>
                                                                     </value>
                                                                  </entity>
                                                               </entity>
                                                            </entity>
                                                         </entity>
                                                         <entity
                                                            logic-type="output-params-mappings">
                                                            <value>
                                                               <map>
                                                                  <entry
                                                                     key="exit"
                                                                     value="innerExit" />
                                                               </map>
                                                            </value>
                                                         </entity>
                                                         <entity
                                                            type="flow-logic"
                                                            logic-type="flow-logic">
                                                            <property
                                                               name="exitLabel"
                                                               value="done" />
                                                         </entity>
                                                      </entity>
                                                   </value>
                                                </entry>
                                             </map>
                                          </value>
                                       </entry>
                                    </map>
                                 </value>
                              </entity>
                              <entity logic-type="dynamic-parameters">
                                 <value>
                                    <map>
                                       <entry key="inputContext"
                                          value="origContext"></entry>
                                       <entry key="entryPointId"
                                          value="entryPointId"></entry>
                                       <entry key="isAsyncContext"
                                          value="isAsyncContext"></entry>
                                    </map>
                                 </value>
                              </entity>
                           </entity>
                        </entity>
                     </value>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="exit"></property>
                              </entity>
                           </value>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="innerExit"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="workflowAdapterEntity" />
         </entity>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/entities/configurable-components/test/parser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../../../dtds/entities.dtd">
<entities>
   <entity id="test.parser" type="configurable-component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  <entry key="inputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="input-parameter">
                                 <property name="name" value="input"></property>
                                 <property name="type" value="String"></property>
                                 <property name="mandatory"
                                    value="true"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
                  <entry key="executionEntity">
                     <value-ref>parserEntity</value-ref>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="result"></property>
                                 <property name="type"
                                    value="List[]"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <entity type="user-params" logic-type="user-parameters">
            
<entity type="config-data">
<property name="templateId" value="TEXT_PARSER"/>
             <property name="userInputParams">
            <value>
               <map>
                                      <entry key="PARSER_SYMBOLS">
   <value>
      <entity type="user-input-parameter">
         <property name="name" value="PARSER_SYMBOLS"></property>
                  <property name="value" value="[&amp;,SEPARATE,amp,true]"></property>
                           <property name="type" value="String"></property>
                           <property name="inputType" value="UNKNOWN_LARGE_VALUE"></property>
                        </entity>
   </value>
</entry>                                </map>
            </value>
         </property>
               
                     
                  </entity>
         </entity>
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="executionEntityWrapper" />
         </entity>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/config/configurable-components/templates/stubs/text_parser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../../../dtds/entities.dtd">
<entities>
   <entity id="${entityDefinition.getId()}" type="configurable-component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  <entry key="inputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="input-parameter">
                                 <property name="name" value="input"></property>
                                 <property name="type" value="String"></property>
                                 <property name="mandatory"
                                    value="true"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
                  <entry key="executionEntity">
                     <value-ref>parserEntity</value-ref>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="result"></property>
                                 <property name="type"
                                    value="List[]"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <entity type="user-params" logic-type="user-parameters">
            #parse("root/config/configurable-components/templates/velocity/config-data-template.xml")
         </entity>
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="executionEntityWrapper" />
         </entity>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/entities/workflows/test-email-sender.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
   <entity id="test-email-sender" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>$workflowDefinition.getDescription()</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  												<entry key="localParameters">
							<value>
								<list>
																	</list>
							</value>
						</entry>
												<entry key="executionEntity">
							<value>
																<entity type="workflow" logic-type="dynamic-wrapper">
   <entity logic-type="config">
      <entity logic-type="executor">
         <entity-ref ref-id="workFlow" />
      </entity>
<!--      <entity logic-type="original-input-name">-->
<!--         <value>inputContext</value>-->
<!--      </entity>-->
      <entity type="workflow-params" logic-type="static-parameters">
         <value>
            <map>
               <entry key="defaultEntryPointId" value="util.net.email-sender_0">
               </entry>
               <entry key="components">
                  <value>
                     <map>
                                                 <entry key="util.net.email-sender_0">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="util.net.email-sender" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
									<entity logic-type="static-parameters">
				<value>
					<map>
													<entry key="recipients">
                                                                                                                  								<value-type value="[individul.x@gmail.com]" type="String"/>
							                                                                                                                  </entry>
													<entry key="subject">
                                                                                                                  								<value-type value="test" type="String"/>
							                                                                                                                  </entry>
													<entry key="message">
                                                                                                                  								<value-type value="test" type="String"/>
							                                                                                                                  </entry>
													<entry key="from">
                                                                                                                  								<value-type value="individul.x@gmail.com" type="String"/>
							                                                                                                                  </entry>
													<entry key="smtpHostName">
                                                                                                                  								<value-type value="smtp.gmail.com" type="String"/>
							                                                                                                                  </entry>
													<entry key="username">
                                                                                                                  								<value-type value="individul.x" type="String"/>
							                                                                                                                  </entry>
													<entry key="password">
                                                                                                                  								<value-type value="xismymiddlename" type="String"/>
							                                                                                                                  </entry>
											</map>
				</value>
			</entity>
								</entity>
	</entity>
</entity>		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="exitLabel" value="exit" />
   </entity>               
                                                </entity>                           </value>
                        </entry>
                                             </map>
                  </value>
               </entry>
            </map>
         </value>
      </entity>
      <entity logic-type="dynamic-parameters">
         <value>
            <map>
               <entry key="inputContext" value="origContext"></entry>
               <entry key="entryPointId" value="entryPointId"></entry>
               <entry key="isAsyncContext" value="isAsyncContext"></entry>
            </map>
         </value>
      </entity>
   </entity>
</entity>						</value>
						</entry>
												<entry key="outputParameters">
							<value>
								<list>
									
																	</list>
							</value>
						</entry>
											</map>
				</value>
			</entity>
			<entity logic-type="original-input-name">
				<value>inputContext</value>
			</entity>
			<entity logic-type="executor">
				<entity-ref ref-id="workflowAdapterEntity" />
			</entity>
		</entity>
	</entity>
</entities>
