=== acionescu/netcell/repository/root/target/test-classes/dtds/entities.dtd
<!ELEMENT list ( value* , value-ref*) >

<!ELEMENT map ( entry+ ) >

<!ELEMENT property ( value? ) >
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST property value-ref NMTOKEN #IMPLIED >
<!ATTLIST property depth CDATA #IMPLIED >

<!ELEMENT entry ( value? , value-ref?, value-type? ) >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry value CDATA #IMPLIED >
<!ATTLIST entry type CDATA #IMPLIED >

<!ELEMENT entity ( value? | entity* | entity-ref* | property* )* >
<!ATTLIST entity type NMTOKEN #IMPLIED >
<!ATTLIST entity logic-type NMTOKEN #IMPLIED >
<!ATTLIST entity id NMTOKEN #IMPLIED >
<!ATTLIST entity value NMTOKEN #IMPLIED >
<!ATTLIST entity class NMTOKEN #IMPLIED >
<!ATTLIST entity init-method CDATA #IMPLIED >
<!ATTLIST entity destroy-method CDATA #IMPLIED >

<!ELEMENT entity-ref EMPTY >
<!ATTLIST entity-ref type NMTOKEN #IMPLIED >
<!ATTLIST entity-ref ref-id NMTOKEN #REQUIRED >

<!ELEMENT entities ( entity* ) >

<!ELEMENT resource ( property* ) >
<!ATTLIST resource class NMTOKEN #REQUIRED >
<!ATTLIST resource id NMTOKEN #IMPLIED >
<!ATTLIST resource init-method CDATA #IMPLIED >
<!ATTLIST resource destroy-method CDATA #IMPLIED >

<!ELEMENT resources ( resource* ) >

<!ELEMENT value ( #PCDATA | list | map | resource | entity )* >

<!ELEMENT value-ref ( #PCDATA ) >

<!ELEMENT value-type EMPTY >
<!ATTLIST value-type value NMTOKEN #REQUIRED >
<!ATTLIST value-type type NMTOKEN #REQUIRED >

=== acionescu/netcell/repository/root/entities/workflows/ro/problems/flows/get-entity-info-by-id.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
   <entity id="ro.problems.flows.get-entity-info-by-id" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>$workflowDefinition.getDescription()</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  						<entry key="inputParameters">
							<value>
								<list>
																		<value>
										<entity type="input-parameter">
	<property name="name" value="entityId"></property>
		<property name="type" value="Number"></property>
				<property name="mandatory" value="true"></property>
	                              <property name="uiType" value="TEXTFIELD"/>
               </entity>								</value>
																		<value>
										<entity type="input-parameter">
	<property name="name" value="userId"></property>
		<property name="type" value="Number"></property>
			                              <property name="uiType" value="TEXTFIELD"/>
               </entity>								</value>
																	</list>
							</value>
						</entry>
																		<entry key="localParameters">
							<value>
								<list>
																		<value>
										<entity type="local-parameter">
	<property name="name" value="subtypesList"></property>
		<property name="type" value="List[Context[id=Number,complex_subtype=String,simple_subtype=String]]"></property>
		</entity>								</value>
																		<value>
										<entity type="local-parameter">
	<property name="name" value="result"></property>
		<property name="type" value="List[Context[]]"></property>
		</entity>								</value>
																		<value>
										<entity type="local-parameter">
	<property name="name" value="tags"></property>
		<property name="type" value="List[Context[]]"></property>
		</entity>								</value>
																	</list>
							</value>
						</entry>
												<entry key="executionEntity">
							<value>
																<entity type="workflow" logic-type="dynamic-wrapper">
   <entity logic-type="config">
      <entity logic-type="executor">
         <entity-ref ref-id="workFlow" />
      </entity>
<!--      <entity logic-type="original-input-name">-->
<!--         <value>inputContext</value>-->
<!--      </entity>-->
      <entity type="workflow-params" logic-type="static-parameters">
         <value>
            <map>
               <entry key="defaultEntryPointId" value="ro.problems.data.get-first-level-subtypes-for-entity-id_0">
               </entry>
               <entry key="components">
                  <value>
                     <map>
                                                 <entry key="ro.problems.data.get-first-level-subtypes-for-entity-id_0">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="ro.problems.data.get-first-level-subtypes-for-entity-id" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
												<entity logic-type="dynamic-parameters">
				<value>
					<map>
													<entry key="entityId" value="entityId"/>
											</map>
				</value>
			</entity>
					</entity>
	</entity>
</entity>		<entity logic-type="output-params-mappings">
		<value>
			<map>
								<entry key="result" value="subtypesList" />
							</map>
		</value>
	</entity>
		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="nextComponentId" value="ro.problems.data.get-entity-info-by-id_1" />
   </entity>               
               </entity>                           </value>
                        </entry>
                                                <entry key="ro.problems.data.get-entity-info-by-id_1">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="ro.problems.data.get-entity-info-by-id" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
												<entity logic-type="dynamic-parameters">
				<value>
					<map>
													<entry key="entityId" value="entityId"/>
													<entry key="subtypesList" value="subtypesList"/>
													<entry key="userId" value="userId"/>
											</map>
				</value>
			</entity>
					</entity>
	</entity>
</entity>		<entity logic-type="output-params-mappings">
		<value>
			<map>
								<entry key="result" value="result" />
							</map>
		</value>
	</entity>
		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="nextComponentId" value="ro.problems.data.get-tags-for-entity_2" />
   </entity>               
                                                </entity>                           </value>
                        </entry>
                                                <entry key="ro.problems.data.get-tags-for-entity_2">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="ro.problems.data.get-tags-for-entity" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
												<entity logic-type="dynamic-parameters">
				<value>
					<map>
													<entry key="entityId" value="entityId"/>
											</map>
				</value>
			</entity>
					</entity>
	</entity>
</entity>		<entity logic-type="output-params-mappings">
		<value>
			<map>
								<entry key="result" value="tags" />
							</map>
		</value>
	</entity>
		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="exitLabel" value="exit" />
   </entity>               
                                                </entity>                           </value>
                        </entry>
                                             </map>
                  </value>
               </entry>
            </map>
         </value>
      </entity>
      <entity logic-type="dynamic-parameters">
         <value>
            <map>
               <entry key="inputContext" value="origContext"></entry>
               <entry key="entryPointId" value="entryPointId"></entry>
               <entry key="isAsyncContext" value="isAsyncContext"></entry>
            </map>
         </value>
      </entity>
   </entity>
</entity>						</value>
						</entry>
												<entry key="outputParameters">
							<value>
								<list>
									
																		<value>
										<entity type="output-parameter">
	<property name="name" value="exit"></property>
		<property name="type" value="String"></property>
	</entity>								</value>
																		<value>
										<entity type="output-parameter">
	<property name="name" value="result"></property>
		<property name="type" value="List[Context[]]"></property>
	</entity>								</value>
																		<value>
										<entity type="output-parameter">
	<property name="name" value="tags"></property>
		<property name="type" value="List[Context[]]"></property>
	</entity>								</value>
																	</list>
							</value>
						</entry>
											</map>
				</value>
			</entity>
			<entity logic-type="original-input-name">
				<value>inputContext</value>
			</entity>
			<entity logic-type="executor">
				<entity-ref ref-id="workflowAdapterEntity" />
			</entity>
		</entity>
	</entity>
</entities>

=== acionescu/netcell/repository/root/entities/workflows/test/parserWf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
   <entity id="test.parserWf" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>$workflowDefinition.getDescription()</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  						<entry key="inputParameters">
							<value>
								<list>
																		<value>
										<entity type="input-parameter">
	<property name="name" value="content"></property>
		<property name="type" value="String"></property>
				<property name="mandatory" value="true"></property>
	</entity>								</value>
																	</list>
							</value>
						</entry>
																		<entry key="localParameters">
							<value>
								<list>
																		<value>
										<entity type="local-parameter">
	<property name="name" value="output"></property>
		<property name="type" value="List[String]"></property>
		</entity>								</value>
																	</list>
							</value>
						</entry>
												<entry key="executionEntity">
							<value>
																<entity type="workflow" logic-type="dynamic-wrapper">
   <entity logic-type="config">
      <entity logic-type="executor">
         <entity-ref ref-id="workFlow" />
      </entity>
<!--      <entity logic-type="original-input-name">-->
<!--         <value>inputContext</value>-->
<!--      </entity>-->
      <entity type="workflow-params" logic-type="static-parameters">
         <value>
            <map>
               <entry key="defaultEntryPointId" value="test.parser_0">
               </entry>
               <entry key="components">
                  <value>
                     <map>
                                                 <entry key="test.parser_0">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="test.parser" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
												<entity logic-type="dynamic-parameters">
				<value>
					<map>
													<entry key="input" value="content"/>
											</map>
				</value>
			</entity>
					</entity>
	</entity>
</entity>		<entity logic-type="output-params-mappings">
		<value>
			<map>
								<entry key="result" value="output" />
							</map>
		</value>
	</entity>
		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="exitLabel" value="exit" />
   </entity>               
                                 <entity type="exit-point-mapping" logic-type="error-mapping">
   </entity>               </entity>                           </value>
                        </entry>
                                             </map>
                  </value>
               </entry>
            </map>
         </value>
      </entity>
      <entity logic-type="dynamic-parameters">
         <value>
            <map>
               <entry key="inputContext" value="origContext"></entry>
               <entry key="entryPointId" value="entryPointId"></entry>
               <entry key="isAsyncContext" value="isAsyncContext"></entry>
            </map>
         </value>
      </entity>
   </entity>
</entity>						</value>
						</entry>
												<entry key="outputParameters">
							<value>
								<list>
									
																		<value>
										<entity type="output-parameter">
	<property name="name" value="exit"></property>
		<property name="type" value="String"></property>
	</entity>								</value>
																		<value>
										<entity type="output-parameter">
	<property name="name" value="output"></property>
		<property name="type" value="List[String]"></property>
	</entity>								</value>
																	</list>
							</value>
						</entry>
											</map>
				</value>
			</entity>
			<entity logic-type="original-input-name">
				<value>inputContext</value>
			</entity>
			<entity logic-type="executor">
				<entity-ref ref-id="workflowAdapterEntity" />
			</entity>
		</entity>
	</entity>
</entities>

=== acionescu/netcell/repository/root/entities/workflows/ro/democracy/consensus/flows/post_question.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
   <entity id="ro.democracy.consensus.flows.post_question" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>$workflowDefinition.getDescription()</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  						<entry key="inputParameters">
							<value>
								<list>
																		<value>
										<entity type="input-parameter">
	<property name="name" value="user_id"></property>
		<property name="type" value="String"></property>
				<property name="mandatory" value="true"></property>
	</entity>								</value>
																		<value>
										<entity type="input-parameter">
	<property name="name" value="question"></property>
		<property name="type" value="String"></property>
				<property name="mandatory" value="true"></property>
	</entity>								</value>
																	</list>
							</value>
						</entry>
																		<entry key="localParameters">
							<value>
								<list>
																	</list>
							</value>
						</entry>
												<entry key="executionEntity">
							<value>
																<entity type="workflow" logic-type="dynamic-wrapper">
   <entity logic-type="config">
      <entity logic-type="executor">
         <entity-ref ref-id="workFlow" />
      </entity>
<!--      <entity logic-type="original-input-name">-->
<!--         <value>inputContext</value>-->
<!--      </entity>-->
      <entity type="workflow-params" logic-type="static-parameters">
         <value>
            <map>
               <entry key="defaultEntryPointId" value="ro.democracy.consensus.post_question_0">
               </entry>
               <entry key="components">
                  <value>
                     <map>
                                                 <entry key="ro.democracy.consensus.post_question_0">
                           <value>                               <entity type="workflow-component">
		<entity type="component" logic-type="component">
	<entity logic-type="dynamic-wrapper">
		<entity logic-type="config">
			<entity logic-type="executor">
				<entity-ref ref-id="ro.democracy.consensus.post_question" />
			</entity>
<!--			<entity logic-type="original-input-name">-->
<!--				<value>argsContext</value>-->
<!--			</entity>-->
												<entity logic-type="dynamic-parameters">
				<value>
					<map>
													<entry key="user_id" value="user_id"/>
													<entry key="question" value="question"/>
											</map>
				</value>
			</entity>
					</entity>
	</entity>
</entity>		
		<entity type="flow-logic" logic-type="flow-logic">
      <property name="exitLabel" value="exit" />
   </entity>               
                                                </entity>                           </value>
                        </entry>
                                             </map>
                  </value>
               </entry>
            </map>
         </value>
      </entity>
      <entity logic-type="dynamic-parameters">
         <value>
            <map>
               <entry key="inputContext" value="origContext"></entry>
               <entry key="entryPointId" value="entryPointId"></entry>
               <entry key="isAsyncContext" value="isAsyncContext"></entry>
            </map>
         </value>
      </entity>
   </entity>
</entity>						</value>
						</entry>
												<entry key="outputParameters">
							<value>
								<list>
									
																	</list>
							</value>
						</entry>
											</map>
				</value>
			</entity>
			<entity logic-type="original-input-name">
				<value>inputContext</value>
			</entity>
			<entity logic-type="executor">
				<entity-ref ref-id="workflowAdapterEntity" />
			</entity>
		</entity>
	</entity>
</entities>

=== acionescu/netcell/repository/root/entities/data-access-entities/ro/problems/login.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../dtds/entities.dtd">
<entities>
   <entity id="ro.problems.login" type="data-access-component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                                    <entry key="inputParameters">
                     <value>
                        <list>
                                                      <value>
                              <entity type="input-parameter">
	<property name="name" value="username"></property>
		<property name="type" value="String"></property>
				<property name="mandatory" value="true"></property>
	                              <property name="uiType" value="TEXTFIELD"/>
               </entity>                           </value>
                                                      <value>
                              <entity type="input-parameter">
	<property name="name" value="password"></property>
		<property name="type" value="String"></property>
				<property name="mandatory" value="true"></property>
	                              <property name="uiType" value="TEXTFIELD"/>
               </entity>                           </value>
                                                   </list>
                     </value>
                  </entry>
                                    <entry key="executionEntity">
                     <value>
                        <entity logic-type="dynamic-wrapper">
                           <entity logic-type="config">
                              <entity 
                                 logic-type="static-parameters">
                                 <value>
                                    <map>
                                       <entry key="commandName"
                                          value="ro.problems.login"></entry>
                                       <entry key="commandManager">
                                          <value>
                                             <entity>
                                                <entity-ref
                                                   ref-id="problems_db" />
                                             </entity>
                                          </value>
                                       </entry>
                                    </map>
                                 </value>
                              </entity>
                              <entity logic-type="executor">
                                 <entity-ref ref-id="dataAccessEntity" />
                              </entity>
                              <entity logic-type="original-input-name">
                                 <value>argsContext</value>
                              </entity>
                           </entity>
                        </entity>
                     </value>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="count"></property>
                                 <property name="type" value="Number"></property>
                              </entity>
                           </value>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="result"></property>
                                 <property name="type"
                                    value="List[Context[]]"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="executionEntityWrapper" />
         </entity>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/entities/components/util/net/resolver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../../../dtds/entities.dtd">
<entities>
   <entity id="util.net.uri-resolver" type="component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  <entry key="inputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="input-parameter">
                                 <property name="name" value="base"></property>
                                 <property name="type" value="String"></property>
                                 <property name="mandatory"
                                    value="true"></property>
                              </entity>
                           </value>
                           <value>
                              <entity type="input-parameter">
                                 <property name="name" value="uri"></property>
                                 <property name="type" value="String"></property>
                                 <property name="mandatory"
                                    value="true"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
                  <entry key="executionEntity">
                     <value>
                        <entity logic-type="dynamic-wrapper">
                           <entity logic-type="config">
                              <entity logic-type="static-parameters">
                                 <value>
                                    <map>
                                       <entry key="resource">
                                          <value-ref>uriResolver</value-ref>
                                       </entry>
                                       <entry key="method" value="resolve" />
                                       <entry key="argsOrder">
                                          <value>
                                             <list>
                                                <value>uri</value>
                                                <value>base</value>
                                             </list>
                                          </value>
                                       </entry>
                                       <entry key="responseMappingName"
                                          value="url" />
                                    </map>
                                 </value>
                              </entity>
                              <entity logic-type="original-input-name">
                                 <value>argsContext</value>
                              </entity>
                              <entity logic-type="executor">
                                 <entity-ref ref-id="methodCaller" />
                              </entity>
                           </entity>
                        </entity>
                     </value>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="url"></property>
                                 <property name="type" value="String"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="executionEntityWrapper" />
         </entity>
      </entity>
   </entity>
</entities>
