=== acionescu/netcell/repository/root/target/test-classes/dtds/entities.dtd
<!ELEMENT list ( value* , value-ref*) >

<!ELEMENT map ( entry+ ) >

<!ELEMENT property ( value? ) >
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST property value-ref NMTOKEN #IMPLIED >
<!ATTLIST property depth CDATA #IMPLIED >

<!ELEMENT entry ( value? , value-ref?, value-type? ) >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry value CDATA #IMPLIED >
<!ATTLIST entry type CDATA #IMPLIED >

<!ELEMENT entity ( value? | entity* | entity-ref* | property* )* >
<!ATTLIST entity type NMTOKEN #IMPLIED >
<!ATTLIST entity logic-type NMTOKEN #IMPLIED >
<!ATTLIST entity id NMTOKEN #IMPLIED >
<!ATTLIST entity value NMTOKEN #IMPLIED >
<!ATTLIST entity class NMTOKEN #IMPLIED >
<!ATTLIST entity init-method CDATA #IMPLIED >
<!ATTLIST entity destroy-method CDATA #IMPLIED >

<!ELEMENT entity-ref EMPTY >
<!ATTLIST entity-ref type NMTOKEN #IMPLIED >
<!ATTLIST entity-ref ref-id NMTOKEN #REQUIRED >

<!ELEMENT entities ( entity* ) >

<!ELEMENT resource ( property* ) >
<!ATTLIST resource class NMTOKEN #REQUIRED >
<!ATTLIST resource id NMTOKEN #IMPLIED >
<!ATTLIST resource init-method CDATA #IMPLIED >
<!ATTLIST resource destroy-method CDATA #IMPLIED >

<!ELEMENT resources ( resource* ) >

<!ELEMENT value ( #PCDATA | list | map | resource | entity )* >

<!ELEMENT value-ref ( #PCDATA ) >

<!ELEMENT value-type EMPTY >
<!ATTLIST value-type value NMTOKEN #REQUIRED >
<!ATTLIST value-type type NMTOKEN #REQUIRED >

=== acionescu/netcell/repository/root/config/configurable-components/configurable-components-templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../dtds/entities.dtd">
<entities>
   <entity id="TEXT_PARSER" type="component-stub">
      <property name="configData">
         <value>
            <entity type="config-data">
               <property name="userInputParams">
                  <value>
                     <map>
                        <entry key="CONFIG_PARAMETERS">
                           <value>
                              <entity type="list-user-input-parameter">
                                 <property name="name"
                                    value="CONFIG_PARAMETERS"></property>
                                 <property name="nestedInputParameter">
                                    <value>
                                       <entity
                                          type="map-user-input-parameter">
                                          <property
                                             name="nestedInputParameters">
                                             <value>
                                                <list>
                                                   <value>
                                                      <entity
                                                         type="user-input-parameter">
                                                         <property
                                                            name="name"
                                                            value="sequence"></property>
                                                      </entity>
                                                   </value>
                                                   <value>
                                                      <entity
                                                         type="user-input-parameter">
                                                         <property
                                                            name="name"
                                                            value="priority"></property>
                                                      </entity>
                                                   </value>
                                                   <value>
                                                      <entity
                                                         type="user-input-parameter">
                                                         <property
                                                            name="name"
                                                            value="type"></property>
                                                         <property
                                                            name="allowedValues">
                                                            <value>
                                                               <list>
                                                                  <value>
                                                                     GROUP_START
                                                                  </value>
                                                                  <value>
                                                                     GROUP_END
                                                                  </value>
                                                                  <value>
                                                                     UNIQUE_GROUP_SEPARATOR
                                                                  </value>
                                                                  <value>
                                                                     ASSOCIATE
                                                                  </value>
                                                                  <value>
                                                                     SEPARATE
                                                                  </value>
                                                               </list>
                                                            </value>
                                                         </property>
                                                      </entity>
                                                   </value>
                                                </list>
                                             </value>
                                          </property>
                                       </entity>
                                    </value>
                                 </property>
                              </entity>
                           </value>
                        </entry>
                     </map>
                  </value>
               </property>
            </entity>
         </value>
      </property>
   </entity>
</entities>

=== acionescu/netcell/repository/root/target/test-classes/xmls/test/workflows.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
<entities>
	<entity id="dynParamsTest" type="dynamic-parameters">
		<value>
			<map>
				<entry key="prmName1" value="prmMapping1"></entry>
				<entry key="prmName2" value="prmMapping2"></entry>
			</map>
		</value>
	</entity>
	<entity id="staticParamsTest" type="static-parameters">
			<value>
				<map>
					<entry key="string" value="strvalue" />
					<entry key="integer" value="5" type="Integer"></entry>
					<entry key="float" value="2.3" type="Float"></entry>
				</map>
			</value>
		</entity>
<!--	-->
<!--	<entity type="workflow">-->
<!--		<entity type="entryPoint" value="comp1" />-->
<!--		<entity type="workflow-components">-->
<!--			<value>-->
<!--				<map>-->
<!--					<entry key="comp1">-->
<!--						<value>-->
<!--							<entity type="workflow-component">-->
<!--								<entity type="workflow-component-input">-->
<!--									<entity type="dynamic-parameters">-->
<!--										<value>-->
<!--											<map>-->
<!--												<entry key="prmName1" value="prmMapping1"></entry>-->
<!--												<entry key="prmName2" value="prmMapping2"></entry>-->
<!--											</map>-->
<!--										</value>-->
<!--									</entity>-->
<!--									<entity type="static-parameters">-->
<!--										<value>-->
<!--											<map>-->
<!--												<entry key="string" value="strvalue" />-->
<!--												<entry key="integer" value="5" type="Integer"></entry>-->
<!--												<entry key="float" value="2.3" type="Float"></entry>-->
<!--											</map>-->
<!--										</value>-->
<!--									</entity>-->
<!--									<entity-ref type="component-ref" ref-id="compRef" />-->
<!--								</entity>-->
<!--								<entity type="workflow-component-output">-->
<!--									<value>-->
<!--										<map>-->
<!--											<entry key="prmName1" value="prmMapping1"></entry>-->
<!--										</map>-->
<!--									</value>-->
<!--								</entity>-->
<!--							</entity>-->
<!--						</value>-->
<!--					</entry>-->
<!--				</map>-->
<!--			</value>-->
<!--		</entity>-->
<!--	</entity>-->
</entities>

=== acionescu/netcell/repository/root/entities/components/core/logic/async/async-call.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../../../../dtds/entities.dtd">
<entities>
   <entity id="core.logic.async.async-call" type="component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  <entry key="fixedExitPoints">
                     <value>
                        <entity type="fixed-exit-points">
                           <property name="exitLabels">
                              <value>
                                 <list>
                                    <value>MAIN</value>
                                    <value>ASYNC</value>
                                 </list>
                              </value>
                           </property>
                           <property name="allowedMappingTypes">
                              <value>
                                 <list>
                                    <value>COMPONENT</value>
                                 </list>
                              </value>
                           </property>
                        </entity>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <property name="entityType" value="10"></property>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/scheduled-jobs/test/test-job.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../dtds/entities.dtd">
<entities>
   <entity id="test.test-job" type="scheduled-job-definition">
      <property name="configData">
         <value>
            <entity type="config-data">
               <property name="userInputParams">
                  <value>
                     <map>
                        <entry key="FLOW_ID">
                           <value>
                              <entity>
                                 <entity type="user-input-parameter">
                                    <property name="name"
                                       value="FLOW_ID"></property>
                                    <property name="value"
                                       value="test.http.urls-processor"></property>
                                    <property name="type"
                                       value="String"></property>
                                 </entity>
                              </entity>
                           </value>
                        </entry>
                        <entry key="FLOW_INPUT_PARAMS">
                           <value>
                              <entity type="user-input-parameter">
                                 <property name="name"
                                    value="FLOW_INPUT_PARAMS"></property>
                                 <property name="value">
                                    <value>
                                       <list>
                                          <value>
                                             <entity
                                                type="user-input-parameter">
                                                <property name="name"
                                                   value="urlCount"></property>
                                                <property name="value"
                                                   value="20"></property>
                                                <property name="type"
                                                   value="Integer"></property>
                                             </entity>
                                          </value>
                                       </list>
                                    </value>
                                 </property>
                              </entity>
                           </value>
                        </entry>
                        <entry key="CRON_TRIGGER">
                           <value>
                              <entity type="user-input-parameter">
                                 <property name="name" value="CRON_TRIGGER"></property>
                                 <property name="value"
                                    value="0/10 * * * * ?"></property>
                                 <property name="type" value="String"></property>
                              </entity>
                           </value>
                        </entry>
                        <entry key="ALLOWED_CONCURENT_JOBS">
                           <value>
                              <entity type="user-input-parameter">
                                 <property name="name"
                                    value="ALLOWED_CONCURENT_JOBS"></property>
                                 <property name="value" value="1"></property>
                                 <property name="type" value="Integer"></property>
                              </entity>
                           </value>
                        </entry>
                        <entry key="MISSFIRE_INSTRUCTION">
                           <value>
                              <entity type="user-input-parameter">
                                 <property name="name"
                                    value="MISSFIRE_INSTRUCTION"></property>
                                 <property name="value"
                                    value="FIRE_WHEN_POSSIBLE"></property>
                                 <property name="type" value="String"></property>
                                 <property name="inputType"
                                    value="VALUE_FROM_LIST"></property>
                                 <property name="allowedValues">
                                    <value>
                                       <list>
                                          <value>FIRE_ONCE_NOW</value>
                                          <value>DO_NOTHING</value>
                                          <value>FIRE_WHEN_POSSIBLE
                                          </value>
                                       </list>
                                    </value>
                                 </property>
                              </entity>
                           </value>
                        </entry>
                     </map>
                  </value>
               </property>
               <property name="dynamicParams">
                  <value>
                     <map>
                        <entry key="MISSFIRE_VALUE">
                           <value>
                              <entity type="dynamic-config-parameter">
                                 <property name="name"
                                    value="MISSFIRE_VALUE"></property>
                                 <property name="sourceParamName"
                                    value="MISSFIRE_INSTRUCTION"></property>
                                 <property name="mappedValues">
                                    <value>
                                       <map>
                                          <entry key="FIRE_ONCE_NOW"
                                             value="1" type="Integer"></entry>
                                          <entry key="DO_NOTHING"
                                             value="2" type="Integer"></entry>
                                          <entry key="FIRE_WHEN_POSSIBLE"
                                             value="3" type="Integer"></entry>
                                       </map>
                                    </value>
                                 </property>
                              </entity>
                           </value>
                        </entry>
                     </map>
                  </value>
               </property>
            </entity>
         </value>
      </property>
   </entity>
</entities>

=== acionescu/netcell/repository/root/config/configurable-components/templates/configurable-component-template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../dtds/entities.dtd">
<entities>
   <entity id="${entityDefinition.getId()}" type="configurable-component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  #if($entityDefinition.getInputParameters()&& $entityDefinition.getInputParameters().size() > 0)
                  <entry key="inputParameters">
                     <value>
                        <list>
                           #foreach($param in $entityDefinition.getInputParameters())
                           <value>
                              #parse("root/config/definitions/templates/input-param-template.xml")
                           </value>
                           #end
                        </list>
                     </value>
                  </entry>
                  #end
                  <entry key="executionEntity">
                     <value>
                        <entity logic-type="dynamic-wrapper">
                           <entity logic-type="config">
                              <entity 
                                 logic-type="static-parameters">
                                 <value>
                                    <map>
                                       <entry key="commandName"
                                          value="${entityDefinition.getCommandName()}"></entry>
                                       <entry key="commandManager">
                                          <value>
                                             <entity>
                                                <entity-ref
                                                   ref-id="${entityDefinition.getDataSourceName()}" />
                                             </entity>
                                          </value>
                                       </entry>
                                    </map>
                                 </value>
                              </entity>
                              <entity logic-type="executor">
                                 <entity-ref ref-id="dataAccessEntity" />
                              </entity>
                              <entity logic-type="original-input-name">
                                 <value>argsContext</value>
                              </entity>
                           </entity>
                        </entity>
                     </value>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="count"></property>
                                 <property name="type" value="Number"></property>
                              </entity>
                           </value>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="result"></property>
                                 <property name="type"
                                    value="List[Context[]]"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="executionEntityWrapper" />
         </entity>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/entities/components/util/parser/html-parser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../../../../dtds/entities.dtd">
<entities>
   <entity id="util.parser.html-parser" type="component-definition"
      logic-type="dynamic-wrapper">
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  <entry key="inputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="input-parameter">
                                 <property name="name" value="input"></property>
                                 <property name="type" value="String"></property>
                                 <property name="mandatory"
                                    value="true"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
                  <entry key="executionEntity">
                     <value>
                        <entity logic-type="dynamic-wrapper">
                           <entity logic-type="config">
                              <entity logic-type="static-parameters">
                                 <value>
                                    <map>
                                       <entry key="resource">
                                          <value>
                                             <resource
                                                id="native.html.parser"
                                                class="ro.zg.util.parser.Parser">
                                                <property
                                                   name="listOfStringSymbols">
                                                   <value>
                                                      <list>
                                                         <value>[&lt;a ,GROUP_START,start_a,true,end_a,end_a2,script_start,apos_start,quot_start,comma,equals],[&gt;,GROUP_END,end_a],[/&gt;,GROUP_END,end_a2],[script&gt;,GROUP_START,script_start,false,script_end],[&lt;/script,GROUP_END,script_end],['\'',GROUP_START:SIMPLE,apos_start,false,apos_end],['\'',GROUP_END,apos_end],[\",GROUP_START:SIMPLE,quot_start,false,quot_end],[\",GROUP_END,quot_end],[ ,SEPARATE,comma],[=,ASSOCIATE,equals]</value>
                                                      </list>
                                                   </value>
                                                </property>
                                             </resource>
                                          </value>
                                       </entry>
                                       <entry key="method" value="parse" />
                                       <entry key="argsOrder">
                                          <value>
                                             <list>
                                                <value>input</value>
                                             </list>
                                          </value>
                                       </entry>
                                       <entry key="complexResponseMappings">
                                          <value>
                                             <list>
                                                <value>
                                                   <map>
                                                      <entry key="methodName" value="getObjectsList"></entry>
                                                      <entry key="mappingName" value="result"></entry>
                                                   </map>
                                                </value>      
                                             </list>
                                          </value>
                                       </entry>
                                    </map>
                                 </value>
                              </entity>
                              <entity logic-type="original-input-name">
                                 <value>argsContext</value>
                              </entity>
                              <entity logic-type="executor">
                                 <entity-ref ref-id="methodCaller" />
                              </entity>
                           </entity>
                        </entity>
                     </value>
                  </entry>
                  <entry key="outputParameters">
                     <value>
                        <list>
                           <value>
                              <entity type="output-parameter">
                                 <property name="name" value="result"></property>
                                 <property name="type" value="List[Context[]]"></property>
                              </entity>
                           </value>
                        </list>
                     </value>
                  </entry>
               </map>
            </value>
         </entity>
                        
         <entity logic-type="original-input-name">
            <value>inputContext</value>
         </entity>
         <entity logic-type="executor">
            <entity-ref ref-id="executionEntityWrapper" />
         </entity>
      </entity>
   </entity>
</entities>

=== acionescu/netcell/repository/root/config/definitions/templates/workflow-definition-template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entities SYSTEM "../../dtds/entities.dtd">
#if($entityDefinition) #set($workflowDefinition = $entityDefinition)
#end
<entities>
   <entity id="$workflowDefinition.getId()" type="workflow-definition"
      logic-type="dynamic-wrapper">
      <entity type="description">
         <value>$workflowDefinition.getDescription()</value>
      </entity>
      <entity logic-type="config">
         <entity type="definition-params" logic-type="static-parameters">
            <value>
               <map>
                  #if($workflowDefinition.getInputParameters()&& $workflowDefinition.getInputParameters().size() > 0)
						<entry key="inputParameters">
							<value>
								<list>
									#foreach($param in $workflowDefinition.getInputParameters())
									<value>
										#parse("root/config/definitions/templates/input-param-template.xml")
								</value>
									#end
								</list>
							</value>
						</entry>
						#end
						#if($workflowDefinition.getLocalParameters())
						<entry key="localParameters">
							<value>
								<list>
									#foreach($param in $workflowDefinition.getLocalParameters())
									<value>
										#parse("root/config/definitions/templates/local-param-template.xml")
								</value>
									#end
								</list>
							</value>
						</entry>
						#end
						<entry key="executionEntity">
							<value>
								#set($workflowConfig = $workflowDefinition.getWorkFlowConfig())
								#parse("root/config/definitions/templates/workflow-template.xml")
						</value>
						</entry>
						#if($workflowDefinition.getOutputParameters())
						<entry key="outputParameters">
							<value>
								<list>
									
									#foreach($param in $workflowDefinition.getOutputParameters())
									<value>
										#parse("root/config/definitions/templates/output-param-template.xml")
								</value>
									#end
								</list>
							</value>
						</entry>
						#end
					</map>
				</value>
			</entity>
			<entity logic-type="original-input-name">
				<value>inputContext</value>
			</entity>
			<entity logic-type="executor">
				<entity-ref ref-id="workflowAdapterEntity" />
			</entity>
		</entity>
	</entity>
</entities>
