=== acionescu/netcell/repository/root/target/test-classes/dtds/resources.dtd
<!ELEMENT list ( value* , value-ref*) >

<!ELEMENT map ( entry+ ) >

<!ELEMENT property ( value? ) >
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST property value-ref NMTOKEN #IMPLIED >
<!ATTLIST property depth CDATA #IMPLIED >

<!ELEMENT entry ( value? , value-ref? ) >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry value CDATA #IMPLIED >

<!ELEMENT resource ( property* ) >
<!ATTLIST resource class NMTOKEN #REQUIRED >
<!ATTLIST resource id NMTOKEN #IMPLIED >
<!ATTLIST resource init-method CDATA #IMPLIED >
<!ATTLIST resource destroy-method CDATA #IMPLIED >

<!ELEMENT resources ( resource* ) >

<!ELEMENT value ( #PCDATA | list | map | resource)* >

<!ELEMENT value-ref ( #PCDATA ) >

=== acionescu/netcell/repository/root/config/distributed-services/processing-node-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../../../dtds/resources.dtd">
<resources>
   <resource id="mainNodeConfiguration"
      class="ro.zg.distributed.framework.cfg.ProcessingNodeConfiguration">
      <property name="groupName" value="NETCELL_SERVICES_TEST"></property>

      <property name="servicesConfiguration">
         <value>
            <list>
               <value>
                  <resource id="ENTITIES_MANAGER"
                     class="ro.zg.distributed.framework.cfg.DistributedServiceConfiguration">
                     <property name="name" value="ENTITIES_MANAGER"></property>
                     <property name="description"
                        value="Manages the netcell entities"></property>
<!--                     <property name="className"-->
<!--                        value="ro.zg.netcell.distributed.EntitiesManagerDistributedService"></property>-->
                     <property name="instance" value-ref="entitiesManagerDs"></property>
                     <property name="mandatory" value="true"></property>
                     <property name="maxNumberOfInstancesPerGroup"
                        value="1"></property>
                  </resource>
               </value>
               <value>
               <resource id="EXECUTION_ENGINE"
                     class="ro.zg.distributed.framework.cfg.DistributedServiceConfiguration">
                     <property name="name" value="EXECUTION_ENGINE"></property>
                     <property name="description"
                        value="Executes flows"></property>
                     <property name="instance" value-ref="executionEngineDs"></property>
                     <property name="mandatory" value="true"></property>
                     <property name="maxNumberOfInstancesPerGroup"
                        value="20000"></property>
<!--                      <property name="runtimeServiceConfig">-->
<!--                        <value>-->
<!--                           <resource id="engineRuntimeConfig" class="ro.zg.distributed.framework.cfg.RuntimeServiceConfiguration">-->
<!--                              <property name="propertiesConfig">-->
<!--                                 <value>-->
<!--                                    <list>-->
<!--                                       <value>-->
<!--                                          <resource id="engineEntitiesProp" class="ro.zg.distributed.framework.cfg.ServicePropertyConfig">-->
<!--                                             <property name="propertyName" value="entities"></property>-->
<!--                                             <property name="sourceServiceName" value="ENTITIES_MANAGER"></property>-->
<!--                                             <property name="methodName" value="getExecutableEntities"></property>-->
<!--                                          </resource>-->
<!--                                       </value>-->
<!--                                    </list>-->
<!--                                 </value>-->
<!--                              </property>-->
<!--                           </resource>-->
<!--                        </value>-->
<!--                      </property>  -->
                  </resource>
               </value>
               
                <value>
                  <resource id="MONITORING_MANAGER"
                     class="ro.zg.distributed.framework.cfg.DistributedServiceConfiguration">
                     <property name="name" value="MONITORING_MANAGER"></property>
                     <property name="description"
                        value="Monitors activity"></property>
                     <property name="instance" value-ref="monitoringManagerDs"></property>
                     <property name="mandatory" value="true"></property>
                     <property name="maxNumberOfInstancesPerGroup"
                        value="1"></property>
                  </resource>
               </value>
               
               <value>
                  <resource id="SCHEDULER" class="ro.zg.distributed.framework.cfg.DistributedServiceConfiguration">
                  <property name="name" value="SCHEDULER"></property>
                     <property name="description"
                        value="Schedules job execution"></property>
                     <property name="instance" value-ref="scheduledJobsManagerDs"></property>
                     <property name="mandatory" value="true"></property>
                     <property name="maxNumberOfInstancesPerGroup"
                        value="1"></property>
                  </resource>
               </value>
            </list>
         </value>
      </property>
   </resource>
   
   <!-- distributed services -->
   
   <resource id="entitiesManagerDs" class="ro.zg.distributed.framework.ReflectionBasedDistributedService">
      <property name="targetObject" value-ref="entitiesManager"></property>
      <property name="argumentsForMethods">
         <value>
            <map>
               <entry key="createEntity.1">
                  <value>
                     <list>
                        <value>ro.zg.netcell.vo.definitions.EntityDefinition</value>
                     </list>
                  </value>
               </entry>
                
               <entry key="updateEntity.1">
                  <value>
                     <list>
                        <value>ro.zg.netcell.vo.definitions.EntityDefinition</value>
                     </list>
                  </value>
               </entry>
               <entry key="removeEntity.1">
                  <value>
                     <list>
                        <value>ro.zg.netcell.vo.definitions.EntityDefinition</value>
                     </list>
                  </value>
               </entry>
            </map>
         </value>
      </property>
   </resource>
   
   <resource id="executionEngineDs" class="ro.zg.distributed.framework.ReflectionBasedDistributedService">
      <property name="targetObject" value-ref="executionEngineController"></property>
      <property name="argumentsForMethods">
         <value>
            <map>
               <entry key="execute.1">
                  <value>
                     <list>
                        <value>ro.zg.util.data.GenericNameValueContext</value>
                     </list>
                  </value>
               </entry>
            </map>
         </value>
      </property>
   </resource>
   
<!--   <resource id="executionEngineDs" class="ro.zg.netcell.distributed.ExecutionEngineDS">-->
<!--      <property name="engine" value-ref="executionEngineController"></property>-->
<!--   </resource>-->
   
   <resource id="monitoringManagerDs" class="ro.zg.distributed.framework.ReflectionBasedDistributedService">
      <property name="targetObject" value-ref="monitoringManager"></property>
      <property name="setResourceLoaderOnStart" value="false"></property>
      <property name="callInitOnStart" value="false"></property>
   </resource>
   
   <resource id="scheduledJobsManagerDs" class="ro.zg.distributed.framework.ReflectionBasedDistributedService">
      <property name="targetObject" value-ref="scheduledJobsManager"></property>
      <!-- init is called by the entities manager -->
      <property name="callInitOnStart" value="false"></property>
   </resource>
   
</resources>

=== acionescu/netcell/repository/root/target/test-classes/root/config/controller/resources-manager.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../../../dtds/resources.dtd">
<resources>
   <resource id="resourcesManager" class="ro.zg.netcell.control.ResourcesManager"
      init-method="init">
      <property name="rootDir" value="root"></property>
      <property name="resourcesRelativePaths">
         <value>
            <map>
               <entry key="DEFINITIONS_HANDLER_FILE"
                  value="config/definitions/definitions-handlers.xml"></entry>
               <entry key="DEFINITIONS_CONFIG_FILE"
                  value="config/definitions/definitions-config.xml"></entry>
               <entry key="ENGINE_HANDLER_FILE" value="config/engine/engine-handlers.xml"></entry>
               <entry key="ENGINE_CONFIG_FILE" value="config/engine/engine-config.xml"></entry>
               <entry key="EXECUTABLE_ENTITIES_DIR" value="entities/workflows"></entry>
               <entry key="BACKUP_DIR" value="backup/entities"></entry>
               <entry key="DEFINITIONS_TEMPLATES_DIR" value="config/definitions/templates"></entry>
               <entry key="DATASOURCES_HANDLER_FILE"
                  value="config/datasources/datasources-handlers.xml"></entry>
               <entry key="DATASOURCES_TEMPLATES_CONFIG_FILE"
                  value="config/datasources/data-sources-templates.xml"></entry>
               <entry key="DATASOURCES_DEFINITIONS_CONFIG_FILE"
                  value="config/datasources/datasources-config.xml"></entry>
               <entry key="DATASOURCES_COMMANDS_HANDLER_FILE"
                  value="config/datasources/datasources-commands-handlers.xml"></entry>
               <entry key="DATASOURCES_COMMANDS_CONFIG_FILE"
                  value="config/datasources/datasources-commands-config.xml"></entry>
               <entry key="DATASOURCES_DIR" value="datasources"></entry>
               <entry key="DATASOURCES_TEMPLATES_DIR" value="config/datasources/templates"></entry>
               <entry key="DATA_ACCESS_COMPONENTS_TEMPLATES_DIR"
                  value="config/datasources/templates/dac"></entry>
               <entry key="DATA_ACCESS_COMPONENTS_CONFIG_FILE"
                  value="config/datasources/data-access-components-config.xml"></entry>
               <entry key="DATA_ACCESS_COMPONENTS_DIR" value="entities/data-access-entities"></entry>
               <entry key="DATASOURCES_COMMAND_TEMPLATE"
                  value="config/datasources/templates/commands/command-template.xml"></entry>
               <entry key="DISTRIBUTED_SERVICES_CONFIG_FILE"
                  value="config/distributed-services/distributed-services-config.xml"></entry>
            </map>
         </value>
      </property>
   </resource>
</resources>
